#!/usr/bin/env node
'use strict';

// F17 immutable third-party binary fixture. This file was not generated by
// STEGO·STUDIO: it is the public Cicada 3301 first-message JPEG, historically
// carrying an OutGuess payload. The regression exercises the production JPEG
// coefficient reader and OutGuess decoder against those frozen bytes.

const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
function assert(c,m){if(!c)throw new Error(m)}
const root=path.join(__dirname,'..');
const fixture=path.join(root,'test','fixtures','third-party','cicada3301_first_message.jpg');
assert(fs.existsSync(fixture),'third-party fixture missing');
const jpeg=new Uint8Array(fs.readFileSync(fixture));
const code=fs.readFileSync(path.join(root,'src','jpeg_dct.js'),'utf8')+'\n'+
  fs.readFileSync(path.join(root,'src','decoder.js'),'utf8');
const api=new Function(code+'\nreturn {decodeJpegCoefficients,ogDecodeJpeg,shDecodeJpeg};')();
const dec=api.decodeJpegCoefficients(jpeg);
const out=api.ogDecodeJpeg(jpeg,'',dec);
assert(out&&out.text,'OutGuess did not recover the frozen third-party fixture');
assert(out.truncated===false,'OutGuess fixture became truncated');
assert(out.len===535,`OutGuess recovered length changed (${out.len})`);
assert(out.text.includes('http://www.reddit.com/r/a2e7j6ic78h0j/'),'expected Cicada URL missing');
assert(out.text.includes('Here is a book code.')&&out.text.endsWith('3301\n'),'expected Cicada body missing');
const digest=crypto.createHash('sha256').update(out.text,'utf8').digest('hex');
assert(digest==='7dbf268b1b356527cf4a2dc105c0dd1f6d2d703291dda24dd9e98e22851d6f40',
  `decoded OutGuess payload changed (${digest})`);
// Different/irrelevant keys may still fall back to OutGuess's default key by
// design; a deliberately mangled JPEG must not recover the frozen payload.
const mangled=new Uint8Array(jpeg); for(let i=100;i<Math.min(220,mangled.length);i++)mangled[i]^=0x5a;
let falsePositive=false;
try{ const d2=api.decodeJpegCoefficients(mangled); const r2=api.ogDecodeJpeg(mangled,'',d2); falsePositive=!!(r2&&r2.text===out.text); }catch(_){ falsePositive=false; }
assert(!falsePositive,'mangled third-party fixture still produced the exact frozen payload');
// Negative corpus: direct third-party recovery can now become terminal evidence,
// so ordinary JPEGs must stay quiet. These frozen files cover gradients/noise,
// flat graphics, hard edges and low-complexity covers at several JPEG qualities.
const cleanDir=path.join(root,'test','fixtures','third-party','clean');
const cleanFiles=fs.readdirSync(cleanDir).filter(n=>/\.jpe?g$/i.test(n)).sort();
assert(cleanFiles.length>=8,'clean JPEG negative corpus too small');
for(const name of cleanFiles){
  const b=new Uint8Array(fs.readFileSync(path.join(cleanDir,name)));
  const d=api.decodeJpegCoefficients(b);
  assert(api.ogDecodeJpeg(b,'',d)===null,`clean JPEG false-positive OutGuess: ${name}`);
}
process.stdout.write(`F17 third-party fixture OK — real OutGuess/Cicada decodes; ${cleanFiles.length} clean JPEGs stay negative`);
